# Site settings

title: CADNAAM project
header-img: img/bg.jpg
email: your-email@yourdomain.com
description: "Collaboration to Accelerate the Discovery of New Alloys for Additive Manufacturing (CADNAAM) project seeks to demonstrate a highly innovative strategy culminating in the design of a new titanium alloy that will exploit the unusual characteristics of additive manufacturing."
baseurl: "/DMREF-Project"
url: "http://mined.gatech.edu"
github_username:  mined-gatech
project_repository: DMREF-Project
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
