# Site settings

title: DMREF Project
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Designing Materials to Revolutionize and Engineer our Future (DMREF) is the primary program by which NSF participates in the Materials Genome Initiative (MGI) for Global Competitiveness."
baseurl: "/DMREF-Project"
url: "http://mined.gatech.edu"
github_username:  mined-gatech
project_repository: DMREF-Project
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
